export const navLinks = [
  {name: "Home", path: "/"},
  {name: "Our Rooms", path: "/room"},
  {name: "Our Facilities", path: "#facilities"},
  {name: "Contact", path: "#contact"},
];

export const roomLinks = [
  {name: "Home", path: "/"},
  {name: "Our Facilities", path: "/#facilities"},
  {name: "Contact", path: "/#contact"},
];

export const rooms = [
  {
    id: 1,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 150000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 2,
    title: "Standard King Sea Facing Room",
    adult: "1 Adult",
    children: "2 Children",
    price: 120000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 3,
    title: "Standard Twin City Facing Room",
    adult: "2 Adult",
    children: "2 Children",
    price: 175000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 4,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 5,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 6,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 7,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 8,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 9,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 10,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 11,
    title: "Standard King City Facing Room",
    adult: "1 Adult",
    children: "1 Children",
    price: 75000,
    rating: 4.49,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
  {
    id: 12,
    title: "Executive room",
    adult: "2 Adult",
    children: "1 Children",
    price: 15000,
    rating: 4.69,
    quantity: 1,
    thumbnail: "/assets/images/room.jpg",
  },
];
