import Contact from "@/components/contact";
import Facilities from "@/components/facilities";
import Header from "@/components/header";
import {Hero} from "@/components/hero";
import Hoteller from "@/components/hoteller";
import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "Home | Tella's Hotel",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Header />
      <main className="">
        <Hero />
        <Hoteller />
        <Facilities />
        <Contact />
      </main>
    </>
  );
}
