import {Hero} from "@/components/hero";
import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "Home | Tella's Hotel",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="">
      <Hero />
    </main>
  );
}
